import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";
import { createDatabase } from "../shared/database/database-provider.js";
import { runMigrations } from "../shared/database/migrate.js";
import { AcceptedPurchase, AcceptedPurchaseId, AcceptedPurchaseLineId, Currency, ExactDecimal, IngredientId, MonetaryAmount, PurchaseId, PurchaseLineId, SqliteAcceptedPurchaseRepository, SupplierId } from "../domains/cost/index.js";
test("Accepted Purchase persists atomically once against Recorded Purchase version",()=>{const directory=mkdtempSync(path.join(tmpdir(),"accepted-purchase-"));const db=createDatabase({databasePath:path.join(directory,"x.sqlite"),host:"127.0.0.1",port:0});try{runMigrations(db);const supplier=SupplierId.fromUuid("aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa"),purchase=PurchaseId.fromUuid("bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb"),sourceLine=PurchaseLineId.fromUuid("cccccccc-cccc-4ccc-8ccc-cccccccccccc");db.execute("INSERT INTO cost_suppliers VALUES (?,?,?,?,?)",[supplier.value,"Supplier","2026-08-23T00:00:00.000Z","o",0]);db.execute("INSERT INTO cost_purchase_aggregates VALUES (?,?,?,?,?,?,?,?,?,?)",[purchase.value,supplier.value,"Recorded","2026-08-23T00:00:00.000Z","o","2026-08-23T00:00:00.000Z","o","2026-08-23T00:00:00.000Z","o",1]);db.execute("INSERT INTO cost_purchase_lines VALUES (?,?,?,?,?,?,?)",[sourceLine.value,purchase.value,0,"ing_dddddddd-dddd-4ddd-8ddd-dddddddddddd","1",0,"kg"]);const accepted=AcceptedPurchase.create({acceptedPurchaseId:AcceptedPurchaseId.fromUuid("eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee"),sourcePurchaseId:purchase,sourcePurchaseVersion:1,supplierId:supplier,currency:Currency.create("TWD"),acceptedAt:"2026-08-23T01:00:00.000Z",acceptedBy:"o",lines:[{acceptedPurchaseLineId:AcceptedPurchaseLineId.fromUuid("ffffffff-ffff-4fff-8fff-ffffffffffff"),sourcePurchaseLineId:sourceLine,ingredientId:IngredientId.fromUuid("dddddddd-dddd-4ddd-8ddd-dddddddddddd"),rawQuantity:ExactDecimal.create("1",0),rawUnitCode:"kg",amount:MonetaryAmount.create("10",0,Currency.create("TWD")),normalizedQuantity:ExactDecimal.create("1000",0),dimension:"mass",canonicalUnitCode:"g",profileId:"measurement_profile_aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",profileVersionId:"measurement_profile_version_aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa"}]});new SqliteAcceptedPurchaseRepository(db).saveNew(accepted,1);assert.equal(db.queryOne<{count:number}>("SELECT count(*) count FROM cost_accepted_purchases")?.count,1);assert.equal(db.queryOne<{count:number}>("SELECT count(*) count FROM cost_accepted_purchase_lines")?.count,1);assert.throws(()=>new SqliteAcceptedPurchaseRepository(db).saveNew(accepted,1));}finally{db.close();rmSync(directory,{recursive:true,force:true});}});
