import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";
import { CostSnapshot, CostSnapshotId, SqliteCostSnapshotRepository, type RecipeCostEvaluationResultV1 } from "../domains/cost/index.js";
import { createDatabase } from "../shared/database/database-provider.js";
import { runMigrations } from "../shared/database/migrate.js";
function result(): RecipeCostEvaluationResultV1 { return { contractName:"RecipeCostEvaluationResult",contractVersion:1,basis:"STANDARD_RECIPE",valuationPolicy:"VAL-2",roundingPolicy:"NONE_EXACT",evaluatedAt:"2026-08-23T01:00:00.000Z",currencyCode:"TWD",recipe:{recipeProjection:{recipeId:"recipe_11111111-1111-4111-8111-111111111111",recipeVersionId:"recipe_version_22222222-2222-4222-8222-222222222222",state:"Published"}},lines:[{linePosition:0,ingredientId:"ing_aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",selectedSource:{sourceType:"ActualPurchase",acceptedPurchaseId:"accepted_purchase_aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",acceptedPurchaseLineId:"accepted_purchase_line_aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa"},exactLineCost:{numerator:"60",denominator:"1"}}],exactStandardBatchCost:{numerator:"60",denominator:"1"},exactPerStandardYieldCost:{numerator:"20",denominator:"1"} } as unknown as RecipeCostEvaluationResultV1; }

test("Snapshot persistence writes header and immutable line trace atomically", () => { const dir=mkdtempSync(path.join(tmpdir(),"cost-snapshot-"));const db=createDatabase({databasePath:path.join(dir,"x.sqlite"),host:"127.0.0.1",port:0});try{runMigrations(db);const snapshot=CostSnapshot.capture({costSnapshotId:CostSnapshotId.fromUuid("aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa"),result:result(),capturedAt:"2026-08-23T02:00:00.000Z",capturedBy:"owner"});new SqliteCostSnapshotRepository(db).saveNew(snapshot);assert.equal(db.queryOne<{count:number}>("SELECT count(*) count FROM cost_recipe_snapshots")?.count,1);const line=db.queryOne<{selected_source_type:string;selected_source_id:string;selected_source_json:string}>("SELECT selected_source_type,selected_source_id,selected_source_json FROM cost_recipe_snapshot_lines");assert.deepEqual({selected_source_type:line?.selected_source_type,selected_source_id:line?.selected_source_id},{selected_source_type:"ActualPurchase",selected_source_id:"accepted_purchase_aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa"});assert.equal(JSON.parse(line?.selected_source_json??"{}").acceptedPurchaseLineId,"accepted_purchase_line_aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa");assert.throws(()=>new SqliteCostSnapshotRepository(db).saveNew(snapshot));assert.equal(db.queryOne<{count:number}>("SELECT count(*) count FROM cost_recipe_snapshots")?.count,1);}finally{db.close();rmSync(dir,{recursive:true,force:true});} });
