import { renderBackOfficeNav, renderNavigationStyles, renderSystemNav } from "../shared/navigation.js";

export function renderAdmin(): string {
  return `<!doctype html>
<html lang="zh-Hant">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>後台管理 | 荒島 ROS</title>
  <style>
    ${renderNavigationStyles()}:root{font-family:Arial,"Noto Sans TC",sans-serif;color:#1e2d35;background:#f4f7f5;--green:#1e5960;--line:#ccd8d5;--muted:#607176;--paper:#fff;--warn:#b44d31}*{box-sizing:border-box}body{margin:0}main{max-width:1240px;margin:0 auto;padding:22px}header{display:flex;justify-content:space-between;align-items:flex-end;gap:14px;border-bottom:2px solid var(--green);padding-bottom:14px}h1{margin:0;font-size:28px}h2{font-size:18px;margin:0 0 14px}.subtitle{margin:4px 0 0;color:var(--muted);font-size:14px}.dashboard{display:grid;grid-template-columns:1fr 1.2fr;gap:16px;margin-top:16px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:16px}.card,section{background:#fff;border:1px solid var(--line);border-radius:7px;padding:16px}.share-list{display:grid;gap:8px}.share-row{display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center}.share-row code{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;background:#eef4f1;padding:9px;border-radius:5px}.qr-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin-top:10px}.qr-box{border:1px dashed #9fb6af;border-radius:6px;padding:12px;min-height:82px;display:grid;place-items:center;text-align:center;color:var(--muted);font-size:13px;background:#fbfdfc}label{display:grid;gap:6px;font-size:13px;color:#40545a;font-weight:700}input,select,textarea,button{font:inherit}input,select,textarea{width:100%;border:1px solid #aebfbc;padding:9px;border-radius:5px;background:#fff}textarea{min-height:68px;resize:vertical}form{display:grid;gap:12px}.row{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.channels{display:flex;flex-wrap:wrap;gap:12px}.channels label{display:flex;align-items:center;gap:5px;font-weight:700}.channels input{width:auto}button{border:0;background:var(--green);color:#fff;padding:10px 12px;border-radius:5px;cursor:pointer;font-weight:800}button.secondary{background:#617477}button.publish{background:var(--warn)}.list{display:grid;gap:8px;margin-top:16px}.item{border:1px solid #d8e1df;padding:10px;display:flex;justify-content:space-between;gap:12px;align-items:center;border-radius:6px}.meta{font-size:12px;color:var(--muted);margin-top:4px}.status{font-size:12px;padding:4px 8px;border-radius:999px;background:#eef1ef}.status.ok,.status.published{background:#dff2e7;color:#13643b}.status.unknown{background:#fff2d1;color:#7a5613}.status.error,.status.inactive{background:#f4e1dc;color:#8a321c}#notice{min-height:22px;color:#13643b;font-weight:800}#notice.error{color:#a52e1b}.versions{margin:8px 0 0;padding-left:18px;font-size:12px;color:#516467}#publication-status{margin:0;color:#40545a}@media(max-width:900px){main{padding:14px}.dashboard,.grid,.row,.share-row,.qr-grid{grid-template-columns:1fr}.item{align-items:flex-start;flex-direction:column}header{align-items:flex-start;flex-direction:column}}
  </style>
</head>
<body>
  ${renderSystemNav("admin")}
  <main>
    <header><div><h1>後台管理</h1><p class="subtitle">商品、場次、資料庫狀態、外部入口與裝置連線集中管理。</p></div><span id="notice"></span></header>
    ${renderBackOfficeNav("catalog")}
    <div class="dashboard">
      <section class="card"><h2>系統狀態</h2><div id="health-card"><span class="status unknown">檢查中</span></div><p class="meta"><a href="/admin/health">查看完整系統狀態</a></p></section>
      <section class="card"><h2>系統入口</h2><div id="share-links" class="share-list"></div><div class="qr-grid"><div class="qr-box">POS QR<br>店員點餐</div><div class="qr-box">Kitchen QR<br>廚房出餐</div><div class="qr-box">Back Office QR<br>管理與檢查</div></div></section>
    </div>
    <div class="grid">
      <section><h2>商品分類</h2><form id="category-form"><input id="category-id" type="hidden"><label>分類代碼<input id="category-code" required pattern="[a-z0-9_-]+"></label><label>分類名稱<input id="category-name" required></label><div class="row"><label>排序<input id="category-sort" type="number" min="0" value="0"></label><label>狀態<select id="category-active"><option value="true">啟用</option><option value="false">停用</option></select></label></div><button type="submit">儲存分類</button></form><div id="categories" class="list"></div></section>
      <section><h2>商品草稿／發布</h2><form id="product-form"><input id="product-id" type="hidden"><div class="row"><label>內部名稱<input id="internal-name" required></label><label>分類<select id="product-category" required></select></label></div><div class="row"><label>顯示名稱<input id="display-name"></label><label>POS 短名稱<input id="pos-name"></label></div><div class="row"><label>售價<input id="selling-price" type="number" min="0"></label><label>狀態<select id="product-status"><option value="draft">草稿</option><option value="inactive">停用</option><option value="published">Published</option></select></label></div><label>描述<textarea id="description"></textarea></label><div class="channels"><label><input type="checkbox" value="pos"> POS</label><label><input type="checkbox" value="kiosk"> Kiosk</label><label><input type="checkbox" value="preorder"> Preorder</label></div><p id="publication-status" class="meta">請先建立並儲存商品草稿</p><div class="row"><button type="submit">儲存草稿</button><button id="publish" type="button" class="publish">正式發布</button></div></form><div id="products" class="list"></div><p class="meta">成本與 BOM 尚未啟用。</p></section>
    </div>
  </main>
  <script>
const state={categories:[],products:[],selectedProductId:null};const $=id=>document.querySelector('#'+id),notice=$('notice');const api=async(path,options={})=>{const response=await fetch(path,{headers:{'content-type':'application/json'},...options}),body=await response.json();if(!response.ok)throw Error(body.error?.message||'請求失敗');return body.data};const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function message(text,error=false){notice.textContent=text;notice.className=error?'error':'';setTimeout(()=>{if(notice.textContent===text)notice.textContent=''},3500)}
function selectedChannels(){return [...document.querySelectorAll('.channels input:checked')].map(input=>input.value)}
function setChannels(values=[]){document.querySelectorAll('.channels input').forEach(input=>input.checked=values.includes(input.value))}
function selectedProduct(){return state.products.find(product=>product.productId===state.selectedProductId)||null}
function resetCategory(){$('category-form').reset();$('category-id').value='';$('category-sort').value='0';$('category-active').value='true'}
function fillProductForm(product){state.selectedProductId=product.productId;$('product-id').value=product.productId;$('internal-name').value=product.internalName;$('product-category').value=product.categoryId;$('display-name').value=product.draft.displayName||'';$('pos-name').value=product.draft.posName||'';$('selling-price').value=product.draft.sellingPrice??'';$('description').value=product.draft.description||'';$('product-status').value=product.status;setChannels(product.draft.channels);const latest=product.versions[0];$('publication-status').textContent=latest?'已發布 v'+latest.versionNumber:'尚未發布'}
function resetProduct(){state.selectedProductId=null;$('product-form').reset();$('product-id').value='';$('product-status').value='draft';setChannels([]);$('publication-status').textContent='請先建立並儲存商品草稿'}
function renderCategories(){const target=$('categories');target.innerHTML=state.categories.map(category=>'<div class="item"><div><strong>'+esc(category.displayName)+'</strong><div class="meta">'+esc(category.code)+' · 排序 '+category.sortOrder+'</div></div><button class="secondary" data-category="'+category.categoryId+'">編輯</button></div>').join('')||'<div class="meta">目前沒有分類</div>';$('product-category').innerHTML='<option value="">選擇分類</option>'+state.categories.filter(category=>category.isActive).map(category=>'<option value="'+category.categoryId+'">'+esc(category.displayName)+'</option>').join('')}
function renderProducts(){const target=$('products');target.innerHTML=state.products.map(product=>'<div class="item"><div><strong>'+esc(product.internalName)+'</strong> <span class="status '+product.status+'">'+product.status+'</span><div class="meta">'+esc(product.draft.displayName||'未填顯示名稱')+' · '+(product.draft.sellingPrice??'未填售價')+' · '+(product.draft.channels.join(', ')||'未選通路')+'</div><ul class="versions">'+product.versions.map(version=>'<li>v'+version.versionNumber+' · '+esc(version.displayName)+' · '+version.sellingPrice+'</li>').join('')+'</ul></div><button class="secondary" data-product="'+product.productId+'">編輯</button></div>').join('')||'<div class="meta">目前沒有商品</div>'}
function renderShareLinks(){const origin=window.location.origin,links=[['POS 點餐','/pos'],['廚房系統','/kitchen'],['後台管理','/admin'],['商品目錄','/admin'],['場次與備貨','/admin/events'],['今日統計','/admin/statistics'],['系統狀態','/admin/health'],['裝置連線','/admin/devices']];$('share-links').innerHTML=links.map(([label,path])=>'<div class="share-row"><code>'+origin+path+'</code><button type="button" data-copy="'+origin+path+'">複製 '+label+'</button></div>').join('')}
async function renderHealth(){try{const health=await api('/health'),event=await api('/api/events/current');$('health-card').innerHTML='<p><span class="status ok">ROS Server 正常</span></p><p><span class="status ok">SQLite 資料庫 '+esc(health.database)+'</span></p><p><span class="status '+(event?'ok':'unknown')+'">目前場次 '+(event?esc(event.displayName):'未開場')+'</span></p><p><span class="status ok">外部入口目前可用</span></p><p class="meta">目前 origin：'+esc(location.origin)+'；瀏覽器無法直接確認 cloudflared process 或上次成功時間，但本頁可讀取代表入口目前可用。</p><p class="meta"><a href="/admin/devices">查看裝置連線</a> · 最後檢查 '+new Date().toLocaleTimeString()+'</p>'}catch(error){$('health-card').innerHTML='<span class="status error">Health 異常</span><p class="meta">'+esc(error.message)+'</p>'}}
async function load(){[state.categories,state.products]=await Promise.all([api('/api/admin/categories'),api('/api/admin/products')]);renderCategories();renderProducts();const product=selectedProduct();if(state.selectedProductId&&!product)resetProduct();else if(product)fillProductForm(product)}
function productPayload(){const product=selectedProduct(),requestedStatus=$('product-status').value,forceDraft=requestedStatus==='published'&&(!product||product.versions.length===0);return {body:{internalName:$('internal-name').value,categoryId:$('product-category').value,displayName:$('display-name').value,posName:$('pos-name').value,sellingPrice:$('selling-price').value===''?undefined:Number($('selling-price').value),description:$('description').value||null,channels:selectedChannels(),status:forceDraft?'draft':requestedStatus},forceDraft}}
$('category-form').addEventListener('submit',async event=>{event.preventDefault();try{const id=$('category-id').value,body={code:$('category-code').value,displayName:$('category-name').value,sortOrder:Number($('category-sort').value),isActive:$('category-active').value==='true'};await api(id?'/api/admin/categories/'+id:'/api/admin/categories',{method:id?'PATCH':'POST',body:JSON.stringify(body)});resetCategory();await load();message('分類已儲存')}catch(error){message(error.message,true)}});
$('product-form').addEventListener('submit',async event=>{event.preventDefault();try{const id=state.selectedProductId,{body,forceDraft}=productPayload(),result=await api(id?'/api/admin/products/'+id:'/api/admin/products',{method:id?'PATCH':'POST',body:JSON.stringify(body)});state.selectedProductId=id||result.productId;await load();message(forceDraft?'草稿已儲存。請使用正式發布建立 published version':'商品草稿已儲存')}catch(error){message(error.message,true)}});
$('publish').addEventListener('click',async()=>{const id=state.selectedProductId;if(!id)return message('請先建立並儲存商品草稿',true);try{const result=await api('/api/admin/products/'+id+'/publish',{method:'POST',body:'{}'});await load();message('已發布 v'+result.version.versionNumber)}catch(error){message(error.message,true)}});
document.addEventListener('click',event=>{const categoryId=event.target.dataset.category,productId=event.target.dataset.product,copy=event.target.dataset.copy;if(categoryId){const category=state.categories.find(item=>item.categoryId===categoryId);$('category-id').value=category.categoryId;$('category-code').value=category.code;$('category-name').value=category.displayName;$('category-sort').value=category.sortOrder;$('category-active').value=String(category.isActive)}if(productId){const product=state.products.find(item=>item.productId===productId);if(product)fillProductForm(product)}if(copy)navigator.clipboard.writeText(copy).then(()=>message('已複製入口'))});
renderShareLinks();renderHealth();load().catch(error=>message(error.message,true));
  </script>
</body>
</html>`;
}
