export function renderAdmin(): string {
  return `<!doctype html>
<html lang="zh-Hant">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Catalog Admin | Desert Island ROS</title>
<style>
  :root{font-family:Arial,sans-serif;color:#1e2d35;background:#f4f7f5}body{margin:0}main{max-width:1180px;margin:0 auto;padding:24px}header{display:flex;justify-content:space-between;align-items:baseline;border-bottom:2px solid #1e5960;padding-bottom:14px}h1{margin:0;font-size:26px}h2{font-size:18px;margin:0 0 16px}.grid{display:grid;grid-template-columns:.8fr 1.2fr;gap:20px;margin-top:20px}section{background:#fff;border:1px solid #ccd8d5;padding:18px}label{display:grid;gap:6px;font-size:13px;color:#40545a}input,select,textarea,button{font:inherit}input,select,textarea{box-sizing:border-box;width:100%;border:1px solid #aebfbc;padding:9px;border-radius:4px;background:#fff}textarea{min-height:68px;resize:vertical}form{display:grid;gap:12px}.row{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.channels{display:flex;flex-wrap:wrap;gap:12px}.channels label{display:flex;align-items:center;gap:5px}.channels input{width:auto}button{border:0;background:#1e5960;color:#fff;padding:9px 12px;border-radius:4px;cursor:pointer}button.secondary{background:#617477}button.publish{background:#b44d31}.list{display:grid;gap:8px;margin-top:16px}.item{border:1px solid #d8e1df;padding:10px;display:flex;justify-content:space-between;gap:12px;align-items:center}.meta{font-size:12px;color:#607176;margin-top:4px}.status{font-size:12px;padding:3px 7px;border-radius:3px;background:#eef1ef}.status.published{background:#dff2e7;color:#13643b}.status.inactive{background:#f4e1dc;color:#8a321c}#notice{min-height:22px;color:#13643b}#notice.error{color:#a52e1b}.versions{margin:8px 0 0;padding-left:18px;font-size:12px;color:#516467}#publication-status{margin:0;color:#40545a}@media(max-width:800px){main{padding:14px}.grid,.row{grid-template-columns:1fr}.item{align-items:flex-start;flex-direction:column}}
</style></head>
<body><main>
  <header><h1>Catalog Admin</h1><span id="notice"></span></header>
  <div class="grid">
    <section><h2>商品分類</h2><form id="category-form"><input id="category-id" type="hidden"><label>代碼<input id="category-code" required pattern="[a-z0-9_-]+"></label><label>名稱<input id="category-name" required></label><div class="row"><label>排序<input id="category-sort" type="number" min="0" value="0"></label><label>狀態<select id="category-active"><option value="true">啟用</option><option value="false">停用</option></select></label></div><button type="submit">儲存分類</button></form><div id="categories" class="list"></div></section>
    <section><h2>商品草稿與發布</h2><form id="product-form"><input id="product-id" type="hidden"><div class="row"><label>內部名稱<input id="internal-name" required></label><label>分類<select id="product-category" required></select></label></div><div class="row"><label>顯示名稱<input id="display-name"></label><label>POS 短名稱<input id="pos-name"></label></div><div class="row"><label>售價<input id="selling-price" type="number" min="0"></label><label>狀態<select id="product-status"><option value="draft">草稿</option><option value="inactive">停用</option><option value="published">已發布</option></select></label></div><label>描述<textarea id="description"></textarea></label><div class="channels"><label><input type="checkbox" value="pos"> POS</label><label><input type="checkbox" value="kiosk"> Kiosk</label><label><input type="checkbox" value="preorder"> Preorder</label></div><p id="publication-status" class="meta">新商品：請先儲存草稿。</p><div class="row"><button type="submit">儲存草稿</button><button id="publish" type="button" class="publish">發布新版本</button></div></form><div id="products" class="list"></div></section>
  </div>
</main><script>
const state={categories:[],products:[],selectedProductId:null};
const $=id=>document.querySelector('#'+id),notice=$('notice');
const api=async(path,options={})=>{const response=await fetch(path,{headers:{'content-type':'application/json'},...options}),body=await response.json();if(!response.ok)throw Error(body.error?.message||'操作失敗');return body.data};
function message(text,error=false){notice.textContent=text;notice.className=error?'error':'';setTimeout(()=>{if(notice.textContent===text)notice.textContent=''},3500)}
function selectedChannels(){return [...document.querySelectorAll('.channels input:checked')].map(input=>input.value)}
function setChannels(values=[]){document.querySelectorAll('.channels input').forEach(input=>input.checked=values.includes(input.value))}
function selectedProduct(){return state.products.find(product=>product.productId===state.selectedProductId)||null}
function resetCategory(){$('category-form').reset();$('category-id').value='';$('category-sort').value='0';$('category-active').value='true'}
function resetProduct(){state.selectedProductId=null;$('product-form').reset();$('product-id').value='';$('product-status').value='draft';setChannels([]);$('publication-status').textContent='新商品：請先儲存草稿。'}
function fillProductForm(product){state.selectedProductId=product.productId;$('product-id').value=product.productId;$('internal-name').value=product.internalName;$('product-category').value=product.categoryId;$('display-name').value=product.draft.displayName||'';$('pos-name').value=product.draft.posName||'';$('selling-price').value=product.draft.sellingPrice??'';$('description').value=product.draft.description||'';$('product-status').value=product.status;setChannels(product.draft.channels);const latest=product.versions[0];$('publication-status').textContent=latest?'已發布 v'+latest.versionNumber:'尚未發布；請確認草稿後使用「發布新版本」。'}
function renderCategories(){const target=$('categories');target.innerHTML=state.categories.map(category=>'<div class="item"><div><strong>'+category.displayName+'</strong><div class="meta">'+category.code+' · 排序 '+category.sortOrder+'</div></div><button class="secondary" data-category="'+category.categoryId+'">編輯</button></div>').join('')||'<div class="meta">尚無分類</div>';$('product-category').innerHTML='<option value="">選擇分類</option>'+state.categories.filter(category=>category.isActive).map(category=>'<option value="'+category.categoryId+'">'+category.displayName+'</option>').join('')}
function renderProducts(){const target=$('products');target.innerHTML=state.products.map(product=>'<div class="item"><div><strong>'+product.internalName+'</strong> <span class="status '+product.status+'">'+product.status+'</span><div class="meta">'+(product.draft.displayName||'尚未填顯示名稱')+' · '+(product.draft.sellingPrice??'未定價')+' 元 · '+(product.draft.channels.join(', ')||'未設通路')+'</div><ul class="versions">'+product.versions.map(version=>'<li>v'+version.versionNumber+' · '+version.displayName+' · '+version.sellingPrice+' 元</li>').join('')+'</ul></div><button class="secondary" data-product="'+product.productId+'">編輯</button></div>').join('')||'<div class="meta">尚無商品</div>'}
async function load(){[state.categories,state.products]=await Promise.all([api('/api/admin/categories'),api('/api/admin/products')]);renderCategories();renderProducts();const product=selectedProduct();if(state.selectedProductId&&!product)resetProduct();else if(product)fillProductForm(product)}
function productPayload(){const product=selectedProduct(),requestedStatus=$('product-status').value,forceDraft=requestedStatus==='published'&&(!product||product.versions.length===0);return {body:{internalName:$('internal-name').value,categoryId:$('product-category').value,displayName:$('display-name').value,posName:$('pos-name').value,sellingPrice:$('selling-price').value===''?undefined:Number($('selling-price').value),description:$('description').value||null,channels:selectedChannels(),status:forceDraft?'draft':requestedStatus},forceDraft}}
$('category-form').addEventListener('submit',async event=>{event.preventDefault();try{const id=$('category-id').value,body={code:$('category-code').value,displayName:$('category-name').value,sortOrder:Number($('category-sort').value),isActive:$('category-active').value==='true'};await api(id?'/api/admin/categories/'+id:'/api/admin/categories',{method:id?'PATCH':'POST',body:JSON.stringify(body)});resetCategory();await load();message('分類已儲存')}catch(error){message(error.message,true)}});
$('product-form').addEventListener('submit',async event=>{event.preventDefault();try{const id=state.selectedProductId,{body,forceDraft}=productPayload(),result=await api(id?'/api/admin/products/'+id:'/api/admin/products',{method:id?'PATCH':'POST',body:JSON.stringify(body)});state.selectedProductId=id||result.productId;await load();message(forceDraft?'草稿已儲存；請使用「發布新版本」建立正式版本。':'商品草稿已儲存')}catch(error){message(error.message,true)}});
$('publish').addEventListener('click',async()=>{const id=state.selectedProductId;if(!id)return message('請先建立並儲存商品草稿',true);try{const result=await api('/api/admin/products/'+id+'/publish',{method:'POST',body:'{}'});await load();message('已發布 v'+result.version.versionNumber)}catch(error){message(error.message,true)}});
document.addEventListener('click',event=>{const categoryId=event.target.dataset.category,productId=event.target.dataset.product;if(categoryId){const category=state.categories.find(item=>item.categoryId===categoryId);$('category-id').value=category.categoryId;$('category-code').value=category.code;$('category-name').value=category.displayName;$('category-sort').value=category.sortOrder;$('category-active').value=String(category.isActive)}if(productId){const product=state.products.find(item=>item.productId===productId);if(product)fillProductForm(product)}});
load().catch(error=>message(error.message,true));
</script></body></html>`;
}
