import type { DatabaseAdapter } from "../../../shared/database/database-adapter.js";
import { CostPersistenceFailure } from "../persistence/errors.js";
import { CostPurchaseVersionConflict } from "../domain/errors.js";
import { CostUnit } from "../domain/cost-unit.js";
import { ExactDecimal } from "../domain/exact-decimal.js";
import { IngredientId, PurchaseId, PurchaseLineId, SupplierId } from "../domain/identities.js";
import type { CostPurchaseRepository } from "../domain/purchase-repository.js";
import { CostPurchase } from "../domain/purchase.js";
import type { CostPurchaseAggregateRow, CostPurchaseLineRow } from "../persistence/purchase-records.js";
function hydrate(header:CostPurchaseAggregateRow, lines:readonly CostPurchaseLineRow[]):CostPurchase{return CostPurchase.rehydrate({purchaseId:PurchaseId.parse(header.purchase_id),supplierId:SupplierId.parse(header.supplier_id),state:header.state,lines:lines.map(line=>({lineId:PurchaseLineId.parse(line.purchase_line_id),ingredientId:IngredientId.parse(line.ingredient_id),quantity:ExactDecimal.create(line.quantity_coefficient,line.quantity_scale),unit:CostUnit.create(line.unit_code)})),createdAt:header.created_at,createdBy:header.created_by,changedAt:header.changed_at,changedBy:header.changed_by,...(header.recorded_at===null?{}:{recordedAt:header.recorded_at,recordedBy:header.recorded_by!}),aggregateVersion:header.aggregate_version});}
export class SqliteCostPurchaseRepository implements CostPurchaseRepository { constructor(private readonly database:DatabaseAdapter){} saveNew(p:CostPurchase):void{try{this.database.transactionImmediate(()=>this.writeNew(p));}catch(error){throw new CostPersistenceFailure("save new Purchase",error);}} findById(id:PurchaseId):CostPurchase|undefined{try{const h=this.database.queryOne<CostPurchaseAggregateRow>("SELECT * FROM cost_purchase_aggregates WHERE purchase_id=?",[id.value]);if(!h)return undefined;const l=this.database.queryMany<CostPurchaseLineRow>("SELECT purchase_line_id,ingredient_id,quantity_coefficient,quantity_scale,unit_code FROM cost_purchase_lines WHERE purchase_id=? ORDER BY line_position",[id.value]);return hydrate(h,l);}catch(error){throw new CostPersistenceFailure("find Purchase",error);}} saveWithExpectedVersion(p:CostPurchase,expected:number):void{try{this.database.transactionImmediate(()=>{const changed=this.database.execute("UPDATE cost_purchase_aggregates SET state=?,changed_at=?,changed_by=?,recorded_at=?,recorded_by=?,aggregate_version=? WHERE purchase_id=? AND aggregate_version=?",[p.state,p.toContract().changedAt,p.toContract().changedBy,p.toContract().recordedAt??null,p.toContract().recordedBy??null,p.aggregateVersion,p.purchaseId.value,expected]).changes;if(changed!==1)throw new CostPurchaseVersionConflict(expected,expected+1);this.database.execute("DELETE FROM cost_purchase_lines WHERE purchase_id=?",[p.purchaseId.value]);this.writeLines(p);});}catch(error){if(error instanceof CostPurchaseVersionConflict)throw error;throw new CostPersistenceFailure("save Purchase with expected version",error);}} private writeNew(p:CostPurchase):void{const c=p.toContract();this.database.execute("INSERT INTO cost_purchase_aggregates VALUES (?,?,?,?,?,?,?,?,?,?)",[c.purchaseId,c.supplierId,c.state,c.createdAt,c.createdBy,c.changedAt,c.changedBy,c.recordedAt??null,c.recordedBy??null,c.aggregateVersion]);this.writeLines(p);} private writeLines(p:CostPurchase):void{p.lines.forEach((line,index)=>this.database.execute("INSERT INTO cost_purchase_lines VALUES (?,?,?,?,?,?,?)",[line.lineId.value,p.purchaseId.value,index,line.ingredientId.value,line.quantity.coefficient,line.quantity.scale,line.unit.code]));} }
