import { randomUUID } from "node:crypto";
import { INGREDIENT_MEASUREMENT_PROFILE_CONTRACT_VERSION, type IngredientMeasurementNormalizationContractV1 } from "../../recipe/index.js";
import { AcceptedPurchase } from "../domain/accepted-purchase.js";
import type { AcceptedPurchaseRepository } from "../domain/accepted-purchase-repository.js";
import { Currency } from "../domain/currency.js";
import { AcceptedPurchaseAlreadyExists, CostDomainError, CostPurchaseInvalidState, CostPurchaseVersionConflict } from "../domain/errors.js";
import { ExactDecimal } from "../domain/exact-decimal.js";
import { AcceptedPurchaseId, AcceptedPurchaseLineId, PurchaseId, PurchaseLineId } from "../domain/identities.js";
import { MonetaryAmount } from "../domain/monetary-amount.js";
import type { CostPurchaseRepository } from "../domain/purchase-repository.js";
import { CostPersistenceFailure } from "../persistence/errors.js";
import { AcceptedPurchaseInvalidStateFailure, AcceptedPurchaseMeasurementFailure, AcceptedPurchaseNotFound, AcceptedPurchasePersistenceFailure, AcceptedPurchaseValidationFailure, AcceptedPurchaseVersionConflictFailure } from "./accepted-purchase-errors.js";

type RawLine = Readonly<{sourcePurchaseLineId:string;amountCoefficient:string;amountScale:number}>;
export type AcceptPurchaseCommand = Readonly<{purchaseId:string;expectedVersion:number;currencyCode:string;lines:readonly RawLine[];acceptedAt:string;acceptedBy:string}>;
function text(value:unknown):string { if(typeof value!=="string"||value.trim().length===0)throw new AcceptedPurchaseValidationFailure(); return value.trim(); }
export class AcceptedPurchaseService {
  constructor(private readonly purchases:Pick<CostPurchaseRepository,"findById">,private readonly accepted:AcceptedPurchaseRepository,private readonly normalization:IngredientMeasurementNormalizationContractV1) {}
  accept(command:AcceptPurchaseCommand){ try { const purchase=this.purchases.findById(PurchaseId.parse(text(command.purchaseId)));if(purchase===undefined)throw new AcceptedPurchaseNotFound();purchase.assertExpectedVersion(command.expectedVersion);if(purchase.state!=="Recorded")throw new AcceptedPurchaseInvalidStateFailure();if(!Array.isArray(command.lines)||command.lines.length!==purchase.lines.length)throw new AcceptedPurchaseValidationFailure();const currency=Currency.create(text(command.currencyCode));const acceptedAt=text(command.acceptedAt);const acceptedBy=text(command.acceptedBy);const amounts=new Map<string,RawLine>();for(const line of command.lines){const sourceId=text(line.sourcePurchaseLineId);if(amounts.has(sourceId))throw new AcceptedPurchaseValidationFailure();amounts.set(sourceId,line);}const lines=purchase.lines.map(source=>{const raw=amounts.get(source.lineId.value);if(raw===undefined)throw new AcceptedPurchaseValidationFailure();const amount=MonetaryAmount.create(text(raw.amountCoefficient),raw.amountScale,currency);const normalized=this.normalization.normalizeAt({contractVersion:INGREDIENT_MEASUREMENT_PROFILE_CONTRACT_VERSION,ingredientId:source.ingredientId.value,rawQuantity:{coefficient:source.quantity.coefficient,scale:source.quantity.scale},rawUnitValue:source.unit.code,evaluatedAt:acceptedAt});if(normalized.status==="failed")throw new AcceptedPurchaseMeasurementFailure();const evidence=normalized.evidence;if(evidence.ingredientId!==source.ingredientId.value||evidence.evaluatedAt!==acceptedAt||evidence.rawUnitValue!==source.unit.code||evidence.measurementEvidence.rawQuantity.coefficient!==source.quantity.coefficient||evidence.measurementEvidence.rawQuantity.scale!==source.quantity.scale)throw new AcceptedPurchaseMeasurementFailure();return {acceptedPurchaseLineId:AcceptedPurchaseLineId.fromUuid(randomUUID()),sourcePurchaseLineId:source.lineId,ingredientId:source.ingredientId,rawQuantity:source.quantity,rawUnitCode:source.unit.code,amount,normalizedQuantity:ExactDecimal.create(evidence.measurementEvidence.normalizedQuantity.coefficient,evidence.measurementEvidence.normalizedQuantity.scale),dimension:evidence.measurementEvidence.dimension,canonicalUnitCode:evidence.measurementEvidence.canonicalUnitCode,profileId:evidence.profileId,profileVersionId:evidence.profileVersionId};});const accepted=AcceptedPurchase.create({acceptedPurchaseId:AcceptedPurchaseId.fromUuid(randomUUID()),sourcePurchaseId:purchase.purchaseId,sourcePurchaseVersion:purchase.aggregateVersion,supplierId:purchase.supplierId,currency,acceptedAt,acceptedBy,lines});this.accepted.saveNew(accepted,command.expectedVersion);return accepted.toContract(); } catch(error){throw this.map(error);} }
  private map(error:unknown):Error {if(error instanceof AcceptedPurchaseValidationFailure||error instanceof AcceptedPurchaseNotFound||error instanceof AcceptedPurchaseInvalidStateFailure||error instanceof AcceptedPurchaseVersionConflictFailure||error instanceof AcceptedPurchaseMeasurementFailure||error instanceof AcceptedPurchasePersistenceFailure)return error;if(error instanceof CostPurchaseVersionConflict)return new AcceptedPurchaseVersionConflictFailure();if(error instanceof CostPurchaseInvalidState||error instanceof AcceptedPurchaseAlreadyExists)return new AcceptedPurchaseInvalidStateFailure();if(error instanceof CostPersistenceFailure)return new AcceptedPurchasePersistenceFailure();if(error instanceof CostDomainError)return new AcceptedPurchaseValidationFailure();return new AcceptedPurchasePersistenceFailure();}
}
