import { Currency } from "./currency.js";
import { ExactDecimal } from "./exact-decimal.js";
import { InvalidAcceptedPurchase } from "./errors.js";
import { AcceptedPurchaseId, AcceptedPurchaseLineId, IngredientId, PurchaseId, PurchaseLineId, SupplierId } from "./identities.js";
import { MonetaryAmount } from "./monetary-amount.js";

export type AcceptedPurchaseLineInput = Readonly<{ acceptedPurchaseLineId: AcceptedPurchaseLineId; sourcePurchaseLineId: PurchaseLineId; ingredientId: IngredientId; rawQuantity: ExactDecimal; rawUnitCode: string; amount: MonetaryAmount; normalizedQuantity: ExactDecimal; dimension: string; canonicalUnitCode: string; profileId: string; profileVersionId: string }>;
export type AcceptedPurchaseLineContractV1 = Readonly<{ acceptedPurchaseLineId:string; sourcePurchaseLineId:string; ingredientId:string; rawQuantityCoefficient:string; rawQuantityScale:number; rawUnitCode:string; amountCoefficient:string; amountScale:number; normalizedQuantityCoefficient:string; normalizedQuantityScale:number; dimension:string; canonicalUnitCode:string; profileId:string; profileVersionId:string }>;
export type AcceptedPurchaseContractV1 = Readonly<{ acceptedPurchaseId:string; sourcePurchaseId:string; sourcePurchaseVersion:number; supplierId:string; currencyCode:string; acceptedAt:string; acceptedBy:string; lines:readonly AcceptedPurchaseLineContractV1[] }>;
export type AcceptedPurchaseInput = Readonly<{acceptedPurchaseId:AcceptedPurchaseId;sourcePurchaseId:PurchaseId;sourcePurchaseVersion:number;supplierId:SupplierId;currency:Currency;acceptedAt:string;acceptedBy:string;lines:readonly AcceptedPurchaseLineInput[]}>;
function text(value:string, field:string):string { if(typeof value!=="string"||value.trim().length===0)throw new InvalidAcceptedPurchase(`${field} must be non-blank.`);return value.trim(); }
function instant(value:string):string { const result=text(value,"acceptedAt");if(!Number.isFinite(Date.parse(result))||new Date(Date.parse(result)).toISOString()!==result)throw new InvalidAcceptedPurchase("acceptedAt must be canonical UTC.");return result; }
export class AcceptedPurchase {
  readonly acceptedPurchaseId:AcceptedPurchaseId; readonly sourcePurchaseId:PurchaseId; readonly sourcePurchaseVersion:number; readonly supplierId:SupplierId; readonly currency:Currency; readonly acceptedAt:string; readonly acceptedBy:string; readonly lines:readonly AcceptedPurchaseLineInput[];
  private constructor(input:AcceptedPurchaseInput){this.acceptedPurchaseId=input.acceptedPurchaseId;this.sourcePurchaseId=input.sourcePurchaseId;if(!Number.isSafeInteger(input.sourcePurchaseVersion)||input.sourcePurchaseVersion<0)throw new InvalidAcceptedPurchase("sourcePurchaseVersion is invalid.");this.sourcePurchaseVersion=input.sourcePurchaseVersion;this.supplierId=input.supplierId;this.currency=input.currency;this.acceptedAt=instant(input.acceptedAt);this.acceptedBy=text(input.acceptedBy,"acceptedBy");if(!Array.isArray(input.lines)||input.lines.length===0)throw new InvalidAcceptedPurchase("Accepted Purchase requires every source line.");const sourceIds=new Set<string>();const lineIds=new Set<string>();for(const line of input.lines){if(sourceIds.has(line.sourcePurchaseLineId.value)||lineIds.has(line.acceptedPurchaseLineId.value))throw new InvalidAcceptedPurchase("Accepted Purchase line identities must be unique.");if(!line.rawQuantity.isPositive||!line.normalizedQuantity.isPositive||line.amount.isNegative)throw new InvalidAcceptedPurchase("Accepted Purchase quantities must be positive and amounts non-negative.");if(!line.dimension.trim()||!line.canonicalUnitCode.trim()||!line.rawUnitCode.trim()||!line.profileId.trim()||!line.profileVersionId.trim())throw new InvalidAcceptedPurchase("Accepted Purchase normalization evidence is incomplete.");if(!line.amount.currency.equals(input.currency))throw new InvalidAcceptedPurchase("Accepted Purchase line currency must match document currency.");sourceIds.add(line.sourcePurchaseLineId.value);lineIds.add(line.acceptedPurchaseLineId.value);}this.lines=Object.freeze([...input.lines]);Object.freeze(this);}
  static create(input:AcceptedPurchaseInput):AcceptedPurchase{return new AcceptedPurchase(input);}
  toContract():AcceptedPurchaseContractV1{return Object.freeze({acceptedPurchaseId:this.acceptedPurchaseId.value,sourcePurchaseId:this.sourcePurchaseId.value,sourcePurchaseVersion:this.sourcePurchaseVersion,supplierId:this.supplierId.value,currencyCode:this.currency.code,acceptedAt:this.acceptedAt,acceptedBy:this.acceptedBy,lines:Object.freeze(this.lines.map(line=>Object.freeze({acceptedPurchaseLineId:line.acceptedPurchaseLineId.value,sourcePurchaseLineId:line.sourcePurchaseLineId.value,ingredientId:line.ingredientId.value,rawQuantityCoefficient:line.rawQuantity.coefficient,rawQuantityScale:line.rawQuantity.scale,rawUnitCode:line.rawUnitCode,amountCoefficient:line.amount.coefficient,amountScale:line.amount.scale,normalizedQuantityCoefficient:line.normalizedQuantity.coefficient,normalizedQuantityScale:line.normalizedQuantity.scale,dimension:line.dimension,canonicalUnitCode:line.canonicalUnitCode,profileId:line.profileId,profileVersionId:line.profileVersionId}))) });}
}
