import { CostUnit } from "./cost-unit.js";
import { CostPurchaseInvalidState, CostPurchaseVersionConflict, InvalidCostPurchase } from "./errors.js";
import { ExactDecimal } from "./exact-decimal.js";
import { IngredientId, PurchaseId, PurchaseLineId, SupplierId } from "./identities.js";

export type CostPurchaseState = "Draft" | "Recorded";
export type CostPurchaseLineInput = Readonly<{ lineId: PurchaseLineId; ingredientId: IngredientId; quantity: ExactDecimal; unit: CostUnit }>;
export type CostPurchaseLineContractV1 = Readonly<{ lineId: string; ingredientId: string; quantityCoefficient: string; quantityScale: number; unitCode: string }>;
export type CostPurchaseContractV1 = Readonly<{ purchaseId: string; supplierId: string; state: CostPurchaseState; lines: readonly CostPurchaseLineContractV1[]; createdAt: string; createdBy: string; changedAt: string; changedBy: string; recordedAt?: string; recordedBy?: string; aggregateVersion: number }>;
export type RehydrateCostPurchase = Readonly<{ purchaseId: PurchaseId; supplierId: SupplierId; state: CostPurchaseState; lines: readonly CostPurchaseLineInput[]; createdAt: string; createdBy: string; changedAt: string; changedBy: string; recordedAt?: string; recordedBy?: string; aggregateVersion: number }>;

function text(value: string, field: string): string { if (typeof value !== "string" || value.trim().length === 0) throw new InvalidCostPurchase(`${field} must be non-blank.`); return value.trim(); }
function instant(value: string, field: string): string { const result=text(value,field); if (!Number.isFinite(Date.parse(result)) || new Date(Date.parse(result)).toISOString() !== result) throw new InvalidCostPurchase(`${field} must be canonical UTC.`); return result; }
function checkedLines(lines: readonly CostPurchaseLineInput[]): readonly CostPurchaseLineInput[] { if (!Array.isArray(lines) || lines.length === 0) throw new InvalidCostPurchase("A Purchase requires at least one line."); const ids=new Set<string>(); for(const line of lines){if(!line.quantity.isPositive)throw new InvalidCostPurchase("Purchase quantity must be positive.");if(ids.has(line.lineId.value))throw new InvalidCostPurchase("Purchase line identities must be unique.");ids.add(line.lineId.value);} return Object.freeze([...lines]); }

export class CostPurchase {
  readonly #purchaseId: PurchaseId; readonly #supplierId: SupplierId; #state: CostPurchaseState; #lines: readonly CostPurchaseLineInput[]; readonly #createdAt: string; readonly #createdBy: string; #changedAt: string; #changedBy: string; #recordedAt: string | undefined; #recordedBy: string | undefined; #aggregateVersion: number;
  private constructor(input: RehydrateCostPurchase) { this.#purchaseId=input.purchaseId;this.#supplierId=input.supplierId;this.#state=input.state;this.#lines=checkedLines(input.lines);this.#createdAt=instant(input.createdAt,"createdAt");this.#createdBy=text(input.createdBy,"createdBy");this.#changedAt=instant(input.changedAt,"changedAt");this.#changedBy=text(input.changedBy,"changedBy");this.#recordedAt=input.recordedAt===undefined?undefined:instant(input.recordedAt,"recordedAt");this.#recordedBy=input.recordedBy===undefined?undefined:text(input.recordedBy,"recordedBy");if(this.#changedAt<this.#createdAt||(this.#recordedAt!==undefined&&this.#recordedAt<this.#createdAt))throw new InvalidCostPurchase("Purchase audit instants must be monotonic.");if((this.#state==="Recorded") !== (this.#recordedAt!==undefined && this.#recordedBy!==undefined))throw new InvalidCostPurchase("Recorded evidence must match Purchase state.");if(!Number.isSafeInteger(input.aggregateVersion)||input.aggregateVersion<0)throw new InvalidCostPurchase("aggregateVersion is invalid.");this.#aggregateVersion=input.aggregateVersion; }
  static createDraft(input: Omit<RehydrateCostPurchase,"state"|"recordedAt"|"recordedBy"|"aggregateVersion"|"changedAt"|"changedBy">): CostPurchase { return new CostPurchase({...input,state:"Draft",changedAt:input.createdAt,changedBy:input.createdBy,aggregateVersion:0}); }
  static rehydrate(input: RehydrateCostPurchase): CostPurchase { return new CostPurchase(input); }
  get purchaseId(){return this.#purchaseId;} get supplierId(){return this.#supplierId;} get state(){return this.#state;} get lines(){return this.#lines;} get aggregateVersion(){return this.#aggregateVersion;}
  assertExpectedVersion(expected:number):void{if(!Number.isSafeInteger(expected)||expected!==this.#aggregateVersion)throw new CostPurchaseVersionConflict(expected,this.#aggregateVersion);}
  revise(lines: readonly CostPurchaseLineInput[], changedAt:string, changedBy:string):void{if(this.#state!=="Draft")throw new CostPurchaseInvalidState(this.#purchaseId.value);const next=instant(changedAt,"occurredAt");if(next<this.#changedAt)throw new InvalidCostPurchase("Purchase audit instants must be monotonic.");this.#lines=checkedLines(lines);this.#changedAt=next;this.#changedBy=text(changedBy,"actor");this.#aggregateVersion+=1;}
  record(recordedAt:string,recordedBy:string):void{if(this.#state!=="Draft")throw new CostPurchaseInvalidState(this.#purchaseId.value);const next=instant(recordedAt,"recordedAt");if(next<this.#changedAt)throw new InvalidCostPurchase("Purchase audit instants must be monotonic.");this.#recordedAt=next;this.#recordedBy=text(recordedBy,"recordedBy");this.#changedAt=this.#recordedAt;this.#changedBy=this.#recordedBy;this.#state="Recorded";this.#aggregateVersion+=1;}
  toContract(): CostPurchaseContractV1{return Object.freeze({purchaseId:this.#purchaseId.value,supplierId:this.#supplierId.value,state:this.#state,lines:Object.freeze(this.#lines.map(line=>Object.freeze({lineId:line.lineId.value,ingredientId:line.ingredientId.value,quantityCoefficient:line.quantity.coefficient,quantityScale:line.quantity.scale,unitCode:line.unit.code}))),createdAt:this.#createdAt,createdBy:this.#createdBy,changedAt:this.#changedAt,changedBy:this.#changedBy,...(this.#recordedAt===undefined?{}:{recordedAt:this.#recordedAt,recordedBy:this.#recordedBy}),aggregateVersion:this.#aggregateVersion});}
}
